### ISSUE TITLE
Creating more readable tests

### ISSUE THREAD

**Issue by nareshbhatia** [WhoopInc/supertest-as-promised#14]
[I realize that this is not a question/issue for supertest-as-promised - just trying to get an opinion from this elite group]

When testing front-ends, there is a great pattern for hiding the low-level details for interacting with the page - it's called the [Page Object](http://martinfowler.com/bliki/PageObject.html). Is it a best practice to do the same when testing REST APIs? Are there any examples of this?

**Detail**
Here's a test written using the Page Object pattern. Note that the details of interacting with the page are encapsulated in the Page Object and hence the test is easily readable:

    describe('Accounts page', function() {

        // Given an account called "BofA Checking"
        // When I change the account name to "Bank of America Checking"
        // Then the accounts page should show an account called "Bank of America Checking"

        it('should allow changing the name of an account', function *() {
            var page = new AccountsPage();

            yield page.createAccount('BofA Checking');

            yield page.changeAccountName('BofA Checking', 'Bank of America Checking');

            var exists = yield page.doesAccountExist('Bank of America Checking');
            expect(exists).to.be.true;
        });
    });

I am wondering if people have attempted similar things at the REST API level? For example:

    describe('Accounts API', function() {

        // Given an account called "BofA Checking"
        // When I change the account name to "Bank of America Checking"
        // Then the accounts page should show an account called "Bank of America Checking"

        it('should allow changing the name of an account', function *() {
            var res = new AccountsResource();

            var account = yield res.createAccount('BofA Checking');

            yield res.changeAccountName(account.id, 'Bank of America Checking');

            var changedAccount = yield res.getAccount(account.id);
            expect(changedAccount.name).to.equal('Bank of America Checking');
        });
    });

**Comment by nareshbhatia** [comment]
I went ahead and implemented the idea. See [here](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/mocha-mocha-supertest/test/specs/accounts.spec.js). Feedback welcome.

**Comment by waisbrot** [comment]
You might get a wider audience at something like http://codereview.stackexchange.com/.

That said, I think that your toy example is fine but I don't see much advantage from it. If you like having a friendly name wrapping your HTTP, consider building that into a JS API for your REST API.

Most of the testing work we do involves the interactions between various resources (e.g. log in as a user, check what team you're on, post some sleep data). For this, we're using Behave (the Python lib for Cucumber).

**Comment by butterflyhug** [comment]
To add a bit more color:

I think the primary reason why we don't use something like Page Objects for our API tests is that we've pushed that kind of organization down into the API design itself.  In UI testing, we use Page Objects to represent the set of actions that a user can take from a particular state of the UI, since there are often a number of different actions available from the same view in the browser.  That idea doesn't directly map to a stateless REST API, but the closest analog is probably the idea of CRUD operations and other transformations that all operate on the same data.  In a well-structured REST API, though, the idea of "multiple actions acting on the same data" is exactly why we have different HTTP methods for the same URL.  So, at WHOOP, we organize our API integration tests into files according to the major subpaths of our URL namespace, and we explicitly state the URL and HTTP method under test inside each test case.

Putting the pieces together, our tests often end up looking something like this:

```cucumber
  Scenario: Try to update someone else's info
    Given I am an authenticated user
    And my id is not equal to 1
    When I PATCH to /users/1 to change my fullName to "X"
    Then I should get a 403 Forbidden status code
    And the response is valid according to the "error" schema
```

We find that it's easy to use this test description to manually create the same request (e.g. using `curl`).  That sometimes comes in handy while debugging, since then it's easy to fiddle with the request parameters to further narrow down the scope of a bug.

All of this said -- if you're trying to test a server that doesn't provide a solidly RESTful API, or if your testers have trouble thinking about URLs and HTTP methods in this way, then it might be a great idea to wrap your URL structures in page objects (or something similar).

**Comment by nareshbhatia** [comment]
@waisbrot, @butterflyhug, thanks for your detailed responses. Still digesting. Can you clarify how you translate the Gherkin shown above to SuperTest? Is that where you use Behave? Also how do you keep your tests DRY? I have found that building reusable wrappers at lower levels makes writing the higher level tests easier. In your example, CRUD for users is needed as background context for higher level tests. This is where I like one-liners to create/update my users etc.

P.S. I am going to close this issue now, but please feel free to comment.

**Comment by waisbrot** [comment]
Nikhil had pointed me at Cucumber for REST testing and I like how it looks. I'm not a huge fan of the TDD style in general, but when I'm looking at REST endpoints I like to think in terms of the HTTP command being executed (like `GET /user/5`). As Lucas said, that's because the endpoint clients are JS, Objective-C, Python, a browser, and Curl so the protocol is the lowest common denominator.

That said, one thing I've been liking about Behave is that we've had a pleasant time using `execute_steps` to define steps in terms of other steps. (This is a Cucumber feature, not specific to the implementing library but it's felt very smooth in Behave.) That means that we've got some very common pieces like

```
Given an authenticated user
...
```

And the step is defined as
```
When I POST to /users with the body:
"""
{ "fullName": "Test Me", "username": "hello", "password":"world" }
"""
Then I get a 200 OK response
When I POST to /auth with the body:
"""
{ "username": "hello", "password":"world" }
"""
Then I get a 200 OK response
And I set the header "Authorization" to {{response.body.token}}
```

However, the goal of that isn't to hide the REST calls. It's just to wrap common sequences up.

None of this relies on Cucumber either. As I said, I just like the way the HTTP commands look.

**Comment by butterflyhug** [comment]
To be clear, we initially started using SuperTest heavily when we were writing integration tests with Mocha and Chai.  We still use those libraries for unit tests, but switched to the Gherkin syntax for integration tests (using first CucumberJS, and now Behave).

We're not using SuperTest with Behave, because it'd just be silly to use a JavaScript library in Python code.

**Comment by butterflyhug** [comment]
@waisbrot If we ever get around to creating that engineering blog, we should maybe write a post about this.  :wink:

**Comment by nareshbhatia** [comment]
@waisbrot, @butterflyhug, thanks for clarifying. I am also a fan of Gherkin (and Specification-by-Example in general), however currently a bit on the fence with CucumberJS. The CucumberJS implementation requires steps to be global which forces data to be passed from step to step in a "global" manner. This could get confusing very quickly. I [asked about this](https://groups.google.com/forum/#!topic/cukes/jKXY1-MVQ2A) on the Cucumber forums, but did not get a response. Curious if behave fixes this issue. For now, I am sticking with Gherkin for specification but implementing it with Mocha - at least it allows each scenario to have its own encapsulated context.

**Comment by waisbrot** [comment]
Not sure what you mean. In general, you _want_ to share state between steps and not between scenarios, and CucumberJS does that. If you're doing something that has the side-effect of polluting the context, you could always clean it up with [an `AfterStep` hook](https://github.com/cucumber/cucumber-js#hooks).

**Comment by nareshbhatia** [comment]
You are correct - I want to share state between steps and not between scenarios. However, CucumberJS does not have the concept of steps within the context of a scenario. All steps are in a "global" namespace! I think that their argument is that the language of the step should be part of the ubiquitous language of the domain, which allows steps to be reused across scenarios. But that also makes the associated state global. See my [world.js](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/cucumberjs-cucumberjs-webdriverio/test/step_definitions/support/world.js) file for what I mean - the global state is sitting in lines 9-11. Here's [more information about this](https://github.com/cucumber/cucumber-js) - look at the discussion about the `World` object: *All step definitions will run with this set to what is known as the World in Cucumber*.

**Comment by butterflyhug** [comment]
Not sure what the issue is, either:

> All step definitions will run with this set to what is known as the World in Cucumber. It's an object exposing useful methods, helpers and variables to your step definitions. **A new instance of World is created before each scenario.**

(emphasis added)

If you're not getting a fresh copy of your World state for each scenario, then maybe your custom World constructor is somehow returning the same instance every time?  I don't think we ever tried to customize the World constructor itself.  We always extended the auto-generated World in our step definition files to get all our necessary functionality, and we had a module of stateles helper functions that the step definitions could import and call, without needing those helpers to exist on the World.

Although, based on your forum post ("I am not comfortable sharing state between various methods of [the World] class..."), it sounds like maybe you're not sold on the idea of sharing a single state object among different steps in the same scenario after all.

**Comment by butterflyhug** [comment]
The nice thing about HTTP-focused steps is that it helps keep things small and stable in the JavaScript-implemented step_definitions and World.  Most of the customized stuff for different topics within the API is actually implemented with Gherkin, as Nate described.  I haven't looked recently, but I think we never wrote more than about 400 lines of JavaScript (or now Python) to implement the step definitions for our entire test suite.  At that point, global state among all steps is less of a problem.

Unfortunately, the JS implementation of Cucumber doesn't seem to support this model as well as Behave does.

**Comment by nareshbhatia** [comment]
@butterflyhug - to clarify, a new world instance is being created for each scenario (as expected). What I am not sold on is sharing the same World definition among completely disconnected scenarios. For example, one scenario may need a single `account` object, so I have a `this.account` in World. Another scenario many need multiple `account` objects, so I add `this.accounts` in World. After a while this gets confusing - should I pick up the account needed for my step from `this.account` or `this.accounts[0]`? Where did the last step drop it in? For a completely different scenario, I may add more state in World. AFAIK, this will keep on growing as my application gets more complex. Am I missing something?

> I haven't looked recently, but I think we never wrote more than about 400 lines of JavaScript (or now Python) to implement the step definitions for our entire test suite. At that point, global state among all steps is less of a problem.

400 lines for your entire test suite? I don't understand this part. My toy domain has only 3 entities (accounts, categories and transactions) and the [world.js](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/cucumberjs-cucumberjs-webdriverio/test/step_definitions/support/world.js) file is already clocking in at 266 lines of uncommented code. Am I misinterpreting your comment?

**Comment by waisbrot** [comment]
773 lines of step definitions similar to
```
  this.Given(/^I POST to (\S+) with the body:$/, function (path, bodyStr, callback) {
    var modBodyStr = helpers.interpolate(this, bodyStr);
    var modPath = helpers.interpolate(this, path);
    helpers.postToPathWithBody(this, callback, modPath, modBodyStr);
  });
```

527 lines of code work like
```
function postToPathWithBody(world, callback, path, body, headers) {
  postToPathWithBodyPromise(world, path, body, headers)
          .then(function (response) {
            world.response = response;
          }).nodeify(callback);
}
```

Adding tests for a new resource generally does not involve adding to either of those files.

**Comment by butterflyhug** [comment]
Yep, it's been too long since I worked on the step definitions and I misremembered the line count (mostly because I forgot the second file).  Thanks, @waisbrot.

**Comment by butterflyhug** [comment]
Back on the main thread re: World state -- I think we always use the equivalent of your `this.accounts` array, and we just default to `this.accounts[0]` for single-account stuff.  In our tests, the state largely corresponds to the major entities in the API -- so we might have `this.accounts` and `this.workouts` and `this.sleeps` (etc) for the current working data sets of each type.

**Comment by nareshbhatia** [comment]
Ok, so I was not going completely crazy :-). I like your convention of only keeping arrays for state - will start doing that. I still think for complex applications (say 20-40 entities in a bounded context), this would really get out of hand.

**Comment by butterflyhug** [comment]
Yeah, I think that depends on the structure of your application.  :smiley:
