### ISSUE TITLE
Long stack traces

### ISSUE THREAD

**Issue by jeremija** [WhoopInc/supertest-as-promised#22]
As this module uses it's own Bluebird module, I propose to add an option to use `BluebirdPromise.longStackTraces()`. I'd be willing to create a pull request if you agree.

The other option would be to list Bluebird as a peer dependency so the user could just do `require('bluebird').longStackTraces()`.

Thanks.

**Comment by benesch** [comment]
FWIW you should be able to do this currently using BYOP: https://github.com/WhoopInc/supertest-as-promised#byop-bring-your-own-promise

But I endorse! Will merge if you send along PR. (Not worried about performance hit if there is one, because if you're using supertest-as-promised in performance-critical code, you're probably doing it wrong.)

**Comment by jeremija** [comment]
Thanke, I must've missed that part with using your own promise. 

I think adding a `longStackTraces()` function might still come in handy for quick debugging so I'll implement it.

**Comment by jeremija** [comment]
On the second thought, I discovered that all instances of Bluebird by default read `BLUEBIRD_DEBUG` environment variable and will [enable long stack traces automatically if this is set to `1`](http://bluebirdjs.com/docs/api/promise.longstacktraces.html) so I do not think implementing long stack traces is necessary. Especially when one can just set a use a custom promise. Sorry for the confusion!

**Comment by benesch** [comment]
No problem! Thanks for your interest.
